apiVersion: batch/v1
kind: Job
metadata:
  name: password-encryption-job
spec:
  template:
    spec:
      containers:
        - name: encrypt-passwords
          image: your-image:latest
          env:
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: s3_bucket
            - name: S3_OBJECT_NAME
              value: "password_data.csv"
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_access_key
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_secret_key
          resources:
            requests:
              cpu: "500m" # Request 0.5 CPU
              memory: "512Mi" # Request 512MB RAM
            limits:
              cpu: "2" # Max 2 CPU cores
              memory: "2Gi" # Max 2GB RAM
      restartPolicy: Never
